services:
  - name: flask-app
    type: web
    env: python
    build:
      path: .
    plan: free
    envVars:
      - key: PORT
        value: "10000"
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:app
